[project]
name = "backend"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "flask>=3.1.2",
<<<<<<< HEAD
    "google-generativeai>=0.8.3",
=======
    "flask-cors>=5.0.0",
    "python-dotenv>=1.0.0",
    "pymongo>=4.6.0",
>>>>>>> 53f56b9912392822f2be7aff50c6610c95e74b44
]
